### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by dominicbarnes** [duojs/test#34]
On my Fedora 20 laptop (and presumably my Ubuntu 14.04 desktop, but I'm not at home atm) `duo-test` does not work very well.

``` sh
$ duo test browser

  Error: Command failed: /bin/sh -c google chrome "http://localhost:60883/test/"
/bin/sh: google: command not found

    at ChildProcess.exithandler (child_process.js:729:12)
    at ChildProcess.EventEmitter.emit (events.js:110:17)
    at maybeClose (child_process.js:992:16)
    at Socket.<anonymous> (child_process.js:1142:11)
    at Socket.EventEmitter.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

On my machine at least, the command is called `google-chrome`, but I'm guessing this is not the case on Mac?

The `name` function is returning `"google chrome"`, which after changing it to `"google-chrome"` it worked. (also noticed `"internet explorer"` should probably be `"iexplorer"`.

**Comment by Frikki** [comment]
Same issue on Linux Mint 17.1.

**Comment by stephenmathieson** [comment]
yeah .. a college had the same issue.  got this stack trace:

```
  Error: Command failed: Unable to find application named 'google chrome'
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

make: *** [test-browser] Error 1
```

but no more information
